name: Build and Run .NET 6 Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t Dockerfile:seleniumcsharp ./SeleniumCSharp

      - name: Run Docker Container
        run: docker run -it --rm Dockerfile:seleniumcsharp
